use symlink for config files

diff --git a/rootfs/usr/share/dc/start b/rootfs/usr/share/dc/start
--- a/rootfs/usr/share/dc/start
+++ b/rootfs/usr/share/dc/start
@@ -3,12 +3,12 @@
 function StartHomeAssistant {
   if test -f ".devcontainer/configuration.yaml"; then
     echo "Copy configuration.yaml"
-    cp -f .devcontainer/configuration.yaml /config || echo ".devcontainer/configuration.yaml are missing"
+    ln -sf "$(GetWorkspaceName).devcontainer/configuration.yaml" /config/configuration.yaml || echo ".devcontainer/configuration.yaml are missing"
   fi
 
   if test -f ".devcontainer/ui-lovelace.yaml"; then
     echo "Copy ui-lovelace.yaml"
-    cp -f .devcontainer/ui-lovelace.yaml /config || echo ""
+    ln -sf "$(GetWorkspaceName).devcontainer/ui-lovelace.yaml" /config/ui-lovelace.yaml || echo ""
   fi
 
   if test -d "custom_components"; then
