Copy entire blueprints folder

diff --git a/rootfs/common/usr/share/container/start b/rootfs/common/usr/share/container/start
--- a/rootfs/common/usr/share/container/start
+++ b/rootfs/common/usr/share/container/start
@@ -16,9 +16,9 @@ function StartHomeAssistant {
     ln -sf "$(GetWorkspaceName).devcontainer/secrets.yaml" /config/secrets.yaml || echo ""
   fi
 
-  if test -d "blueprints/automation"; then
+  if test -d "blueprints"; then
     echo "Copy automation blueprints"
-    cp -r blueprints/automation/* /config/blueprints/automation/ || echo "Failed to copy automation blueprints"
+    cp -r blueprints/* /config/blueprints/ || echo "Failed to copy blueprints"
   fi
 
   if test -d "custom_components"; then
