Add absolute path as per request

diff --git a/rootfs/common/usr/share/container/start b/rootfs/common/usr/share/container/start
--- a/rootfs/common/usr/share/container/start
+++ b/rootfs/common/usr/share/container/start
@@ -1,27 +1,27 @@
 #!/bin/bash
 
 function StartHomeAssistant {
-  if test -f ".devcontainer/configuration.yaml"; then
+  if test -f "$(GetWorkspaceName).devcontainer/configuration.yaml"; then
     echo "Copy configuration.yaml"
     ln -sf "$(GetWorkspaceName).devcontainer/configuration.yaml" /config/configuration.yaml || echo ".devcontainer/configuration.yaml are missing"
   fi
 
-  if test -f ".devcontainer/ui-lovelace.yaml"; then
+  if test -f "$(GetWorkspaceName).devcontainer/ui-lovelace.yaml"; then
     echo "Copy ui-lovelace.yaml"
     ln -sf "$(GetWorkspaceName).devcontainer/ui-lovelace.yaml" /config/ui-lovelace.yaml || echo ""
   fi
 
-  if test -f ".devcontainer/secrets.yaml"; then
+  if test -f "$(GetWorkspaceName).devcontainer/secrets.yaml"; then
     echo "Copy secrets.yaml"
     ln -sf "$(GetWorkspaceName).devcontainer/secrets.yaml" /config/secrets.yaml || echo ""
   fi
 
-  if test -d "blueprints"; then
+  if test -d "$(GetWorkspaceName)blueprints"; then
     echo "Copy automation blueprints"
-    cp -r blueprints/* /config/blueprints/ || echo "Failed to copy blueprints"
+    cp -r $(GetWorkspaceName)blueprints/* /config/blueprints/ || echo "Failed to copy blueprints"
   fi
 
-  if test -d "custom_components"; then
+  if test -d "$(GetWorkspaceName)custom_components"; then
     echo "Symlink the custom component directory"
 
     if test -d "custom_components"; then
@@ -29,7 +29,7 @@ function StartHomeAssistant {
     fi
 
     ln -sf "$(GetWorkspaceName)custom_components/" /config/custom_components || echo "Could not copy the custom_component" exit 1
-  elif  test -f "__init__.py"; then
+  elif  test -f "$(GetWorkspaceName)__init__.py"; then
     echo "Having the component in the root is currently not supported"
   fi
 
